In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1")

/home/anky/.local/lib/python3.10/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/home/anky/.local/lib/python3.10/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [3]:
action_space_size = env.action_space.n
print(f"action_space_size: {action_space_size}")
state_space_size = env.observation_space.n
print(f"state_space_size: {state_space_size}")

action_space_size: 4
state_space_size: 16


In [4]:
q_table = np.zeros((state_space_size,action_space_size))
q_table # state-action-values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
num_episodes = 1000
max_steps_per_episode = 100

learning_rate = 0.1 # alpha
discount_factor = 0.99 # gamma

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [9]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()
    done = False
    reward_current_episode = 0
    
    for step in range(max_steps_per_episode):
        print(f"reward_current_episode: {reward_current_episode}",end="\r")
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        # print(env.step(action))
        new_state,reward,done,info = env.step(action)
        # print(f"current_reward: {reward}",end="\r")

        q_table[state,action] = q_table[state,action] * (1-learning_rate) + learning_rate*(reward+discount_factor*np.max(q_table[new_state,:]))
        state = new_state
        reward_current_episode+=reward
        
        
        if done:
            break

        exploration_rate = min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episode)
        rewards_all_episodes.append(reward_current_episode)


In [10]:
print(q_table)

[[0.54134922 0.50472564 0.51080434 0.50859166]
 [0.39947627 0.23358621 0.16856744 0.44370717]
 [0.37718398 0.36001374 0.34476216 0.40172678]
 [0.2363404  0.17676406 0.23434508 0.38509126]
 [0.57139573 0.37597943 0.4151164  0.36754113]
 [0.         0.         0.         0.        ]
 [0.29171859 0.12517605 0.31432313 0.1103435 ]
 [0.         0.         0.         0.        ]
 [0.35372542 0.34351956 0.47939289 0.59638914]
 [0.44085402 0.65699657 0.41160991 0.32749202]
 [0.52099791 0.50527426 0.36605235 0.26752291]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54308326 0.55279227 0.75407594 0.49485714]
 [0.697638   0.84539366 0.7919796  0.80210168]
 [0.         0.         0.         0.        ]]
